"""initial schema

Revision ID: 6ad3a855090b
Revises: 
Create Date: 2026-08-31 11:40:17.542042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.models.database import FlexibleJSONB, FlexibleJSON


# revision identifiers, used by Alembic.
revision: str = '6ad3a855090b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('university', sa.String(length=200), nullable=True),
    sa.Column('expertise_areas', FlexibleJSONB(), nullable=True),
    sa.Column('career_field', sa.String(length=200), nullable=True),
    sa.Column('citation_count', sa.Integer(), nullable=True),
    sa.Column('publications_count', sa.Integer(), nullable=True),
    sa.Column('interest_score', sa.Integer(), nullable=True),
    sa.Column('subscription_status', sa.String(length=20), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(), nullable=True),
    sa.Column('subscription_ends_at', sa.DateTime(), nullable=True),
    sa.Column('paystack_customer_id', sa.String(length=100), nullable=True),
    sa.Column('paystack_subscription_id', sa.String(length=100), nullable=True),
    sa.Column('has_given_feedback', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('bounties',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('creator_id', sa.String(length=50), nullable=False),
    sa.Column('paper_id', sa.String(length=100), nullable=True),
    sa.Column('paper_title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amount_kes', sa.Integer(), nullable=True),
    sa.Column('reputation_points', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('paystack_reference', sa.String(length=100), nullable=True),
    sa.Column('funded', sa.Boolean(), nullable=True),
    sa.Column('awarded_to_user_id', sa.String(length=50), nullable=True),
    sa.Column('awarded_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['awarded_to_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bounties_id'), 'bounties', ['id'], unique=False)
    op.create_index('ix_bounties_status_funded', 'bounties', ['status', 'funded'], unique=False)
    op.create_table('connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.String(length=50), nullable=False),
    sa.Column('followed_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connections_id'), 'connections', ['id'], unique=False)
    op.create_table('deep_research_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('interaction_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_deep_research_interaction_id', 'deep_research_sessions', ['interaction_id'], unique=False)
    op.create_index(op.f('ix_deep_research_sessions_id'), 'deep_research_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_deep_research_sessions_interaction_id'), 'deep_research_sessions', ['interaction_id'], unique=False)
    op.create_table('draft_anchors',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('external_anchor_ref', sa.String(length=500), nullable=True),
    sa.Column('anchored_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draft_anchors_content_hash'), 'draft_anchors', ['content_hash'], unique=False)
    op.create_index(op.f('ix_draft_anchors_id'), 'draft_anchors', ['id'], unique=False)
    op.create_table('ghost_profiles',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('orcid_id', sa.String(length=30), nullable=True),
    sa.Column('affiliation', sa.String(length=300), nullable=True),
    sa.Column('co_publication_dois', FlexibleJSONB(), nullable=True),
    sa.Column('claimed_by_user_id', sa.String(length=50), nullable=True),
    sa.Column('invite_sent_at', sa.DateTime(), nullable=True),
    sa.Column('invite_token', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['claimed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ghost_profiles_email'), 'ghost_profiles', ['email'], unique=False)
    op.create_index(op.f('ix_ghost_profiles_id'), 'ghost_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_ghost_profiles_invite_token'), 'ghost_profiles', ['invite_token'], unique=True)
    op.create_index(op.f('ix_ghost_profiles_orcid_id'), 'ghost_profiles', ['orcid_id'], unique=False)
    op.create_table('institutional_sandboxes',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('institution', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('admin_user_id', sa.String(length=50), nullable=False),
    sa.Column('invite_code', sa.String(length=20), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('event_start', sa.DateTime(), nullable=True),
    sa.Column('event_end', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institutional_sandboxes_id'), 'institutional_sandboxes', ['id'], unique=False)
    op.create_index(op.f('ix_institutional_sandboxes_invite_code'), 'institutional_sandboxes', ['invite_code'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index('ix_notifications_user_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_table('orcid_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('orcid_id', sa.String(length=30), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_orcid_profiles_id'), 'orcid_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_orcid_profiles_orcid_id'), 'orcid_profiles', ['orcid_id'], unique=True)
    op.create_table('orcid_publications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('put_code', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('doi', sa.String(length=200), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('journal', sa.String(length=300), nullable=True),
    sa.Column('work_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orcid_publications_doi'), 'orcid_publications', ['doi'], unique=False)
    op.create_index(op.f('ix_orcid_publications_id'), 'orcid_publications', ['id'], unique=False)
    op.create_table('research_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_projects_id'), 'research_projects', ['id'], unique=False)
    op.create_table('research_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('papers_count', sa.Integer(), nullable=True),
    sa.Column('synthesis_length', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_sessions_id'), 'research_sessions', ['id'], unique=False)
    op.create_table('saved_papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('paper_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('filters', FlexibleJSONB(), nullable=True),
    sa.Column('authors', FlexibleJSONB(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('citations', sa.Integer(), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_papers_id'), 'saved_papers', ['id'], unique=False)
    op.create_index('ix_saved_papers_user_id', 'saved_papers', ['user_id'], unique=False)
    op.create_table('search_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('results_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_history_id'), 'search_history', ['id'], unique=False)
    op.create_index('ix_search_history_user_id', 'search_history', ['user_id'], unique=False)
    op.create_table('trial_feedback',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('favorite_feature', sa.String(length=50), nullable=True),
    sa.Column('improvement_text', sa.Text(), nullable=True),
    sa.Column('would_recommend', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trial_feedback_id'), 'trial_feedback', ['id'], unique=False)
    op.create_table('uploaded_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('cid', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploaded_files_id'), 'uploaded_files', ['id'], unique=False)
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('theme', sa.String(length=20), nullable=True),
    sa.Column('default_paper_limit', sa.Integer(), nullable=True),
    sa.Column('llm_provider', sa.String(length=20), nullable=True),
    sa.Column('llm_model', sa.String(length=50), nullable=True),
    sa.Column('auto_export', sa.Boolean(), nullable=True),
    sa.Column('export_format', sa.String(length=20), nullable=True),
    sa.Column('preferences', FlexibleJSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_settings_id'), 'user_settings', ['id'], unique=False)
    op.create_table('bounty_submissions',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('bounty_id', sa.String(length=50), nullable=False),
    sa.Column('submitter_id', sa.String(length=50), nullable=False),
    sa.Column('review_text', sa.Text(), nullable=False),
    sa.Column('is_winner', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bounty_id'], ['bounties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bounty_submissions_bounty_id', 'bounty_submissions', ['bounty_id'], unique=False)
    op.create_index(op.f('ix_bounty_submissions_id'), 'bounty_submissions', ['id'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags', FlexibleJSON(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_id'), 'notes', ['id'], unique=False)
    op.create_index('ix_notes_user_id', 'notes', ['user_id'], unique=False)
    op.create_table('project_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_activities_id'), 'project_activities', ['id'], unique=False)
    op.create_table('project_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_members_id'), 'project_members', ['id'], unique=False)
    op.create_table('sandbox_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sandbox_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sandbox_id'], ['institutional_sandboxes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sandbox_members_id'), 'sandbox_members', ['id'], unique=False)
    op.create_index('ix_sandbox_members_sandbox_user', 'sandbox_members', ['sandbox_id', 'user_id'], unique=True)
    op.create_table('saved_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('papers', FlexibleJSONB(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('tags', FlexibleJSONB(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=True),
    sa.Column('vector_id', sa.String(length=100), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_queries_id'), 'saved_queries', ['id'], unique=False)
    op.create_index('ix_saved_queries_user_id', 'saved_queries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_saved_queries_user_id', table_name='saved_queries')
    op.drop_index(op.f('ix_saved_queries_id'), table_name='saved_queries')
    op.drop_table('saved_queries')
    op.drop_index('ix_sandbox_members_sandbox_user', table_name='sandbox_members')
    op.drop_index(op.f('ix_sandbox_members_id'), table_name='sandbox_members')
    op.drop_table('sandbox_members')
    op.drop_index(op.f('ix_project_members_id'), table_name='project_members')
    op.drop_table('project_members')
    op.drop_index(op.f('ix_project_activities_id'), table_name='project_activities')
    op.drop_table('project_activities')
    op.drop_index('ix_notes_user_id', table_name='notes')
    op.drop_index(op.f('ix_notes_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_bounty_submissions_id'), table_name='bounty_submissions')
    op.drop_index('ix_bounty_submissions_bounty_id', table_name='bounty_submissions')
    op.drop_table('bounty_submissions')
    op.drop_index(op.f('ix_user_settings_id'), table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_uploaded_files_id'), table_name='uploaded_files')
    op.drop_table('uploaded_files')
    op.drop_index(op.f('ix_trial_feedback_id'), table_name='trial_feedback')
    op.drop_table('trial_feedback')
    op.drop_index('ix_search_history_user_id', table_name='search_history')
    op.drop_index(op.f('ix_search_history_id'), table_name='search_history')
    op.drop_table('search_history')
    op.drop_index('ix_saved_papers_user_id', table_name='saved_papers')
    op.drop_index(op.f('ix_saved_papers_id'), table_name='saved_papers')
    op.drop_table('saved_papers')
    op.drop_index(op.f('ix_research_sessions_id'), table_name='research_sessions')
    op.drop_table('research_sessions')
    op.drop_index(op.f('ix_research_projects_id'), table_name='research_projects')
    op.drop_table('research_projects')
    op.drop_index(op.f('ix_orcid_publications_id'), table_name='orcid_publications')
    op.drop_index(op.f('ix_orcid_publications_doi'), table_name='orcid_publications')
    op.drop_table('orcid_publications')
    op.drop_index(op.f('ix_orcid_profiles_orcid_id'), table_name='orcid_profiles')
    op.drop_index(op.f('ix_orcid_profiles_id'), table_name='orcid_profiles')
    op.drop_table('orcid_profiles')
    op.drop_index('ix_notifications_user_read', table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_institutional_sandboxes_invite_code'), table_name='institutional_sandboxes')
    op.drop_index(op.f('ix_institutional_sandboxes_id'), table_name='institutional_sandboxes')
    op.drop_table('institutional_sandboxes')
    op.drop_index(op.f('ix_ghost_profiles_orcid_id'), table_name='ghost_profiles')
    op.drop_index(op.f('ix_ghost_profiles_invite_token'), table_name='ghost_profiles')
    op.drop_index(op.f('ix_ghost_profiles_id'), table_name='ghost_profiles')
    op.drop_index(op.f('ix_ghost_profiles_email'), table_name='ghost_profiles')
    op.drop_table('ghost_profiles')
    op.drop_index(op.f('ix_draft_anchors_id'), table_name='draft_anchors')
    op.drop_index(op.f('ix_draft_anchors_content_hash'), table_name='draft_anchors')
    op.drop_table('draft_anchors')
    op.drop_index(op.f('ix_deep_research_sessions_interaction_id'), table_name='deep_research_sessions')
    op.drop_index(op.f('ix_deep_research_sessions_id'), table_name='deep_research_sessions')
    op.drop_index('ix_deep_research_interaction_id', table_name='deep_research_sessions')
    op.drop_table('deep_research_sessions')
    op.drop_index(op.f('ix_connections_id'), table_name='connections')
    op.drop_table('connections')
    op.drop_index('ix_bounties_status_funded', table_name='bounties')
    op.drop_index(op.f('ix_bounties_id'), table_name='bounties')
    op.drop_table('bounties')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
