"""
PDF Export API
==============
Renders a research synthesis as a two-column academic PDF using WeasyPrint.
Falls back to plain-text PDF if WeasyPrint is unavailable.
"""

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import Response
from pydantic import BaseModel, Field
from typing import Optional, List
from datetime import datetime

from app.core.security import get_current_user
from app.core.logger import get_logger

logger = get_logger("export_api")
router = APIRouter()


class ExportRequest(BaseModel):
    title: str = Field(..., min_length=1, max_length=300)
    synthesis: str = Field(..., min_length=1)
    query: Optional[str] = None
    authors: List[str] = []
    language: str = "English"


_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<style>
  @page {{
    size: A4;
    margin: 2cm 2.5cm;
  }}
  body {{
    font-family: 'Times New Roman', Times, serif;
    font-size: 10pt;
    line-height: 1.5;
    color: #111;
  }}
  h1 {{
    font-size: 16pt;
    text-align: center;
    margin-bottom: 4pt;
  }}
  .meta {{
    text-align: center;
    font-size: 9pt;
    color: #555;
    margin-bottom: 16pt;
    border-bottom: 1px solid #ccc;
    padding-bottom: 8pt;
  }}
  .columns {{
    column-count: 2;
    column-gap: 1.2cm;
    text-align: justify;
  }}
  .label {{
    font-size: 8pt;
    font-weight: bold;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    color: #444;
    margin-top: 12pt;
  }}
  p {{
    margin: 0 0 8pt 0;
  }}
  .footer {{
    margin-top: 24pt;
    border-top: 1px solid #ccc;
    padding-top: 6pt;
    font-size: 8pt;
    color: #888;
    text-align: center;
  }}
</style>
</head>
<body>
  <h1>{title}</h1>
  <div class="meta">
    {authors_line}
    {query_line}
    Generated by Tafiti AI &bull; {date}
  </div>
  <div class="columns">
    {synthesis_paragraphs}
  </div>
  <div class="footer">
    Tafiti AI &bull; tafitiai.co.ke &bull; Research at the Speed of Thought
  </div>
</body>
</html>
"""


def _render_html(req: ExportRequest) -> str:
    authors_line = (
        f"<div>{', '.join(req.authors)}</div>" if req.authors else ""
    )
    query_line = (
        f"<div>Research Query: <em>{req.query}</em></div>" if req.query else ""
    )
    paragraphs = "".join(
        f"<p>{para.strip()}</p>"
        for para in req.synthesis.split("\n\n")
        if para.strip()
    )
    return _HTML_TEMPLATE.format(
        title=req.title,
        authors_line=authors_line,
        query_line=query_line,
        synthesis_paragraphs=paragraphs,
        date=datetime.utcnow().strftime("%B %d, %Y"),
    )


@router.post("/pdf")
async def export_pdf(
    body: ExportRequest,
    current_user: dict = Depends(get_current_user),
):
    """Export a synthesis as a two-column academic PDF."""
    html = _render_html(body)

    try:
        from weasyprint import HTML
        pdf_bytes = HTML(string=html).write_pdf()
    except ImportError:
        raise HTTPException(
            status_code=501,
            detail="PDF export requires WeasyPrint. Please install it on the server.",
        )
    except Exception as e:
        logger.error(f"WeasyPrint render failed: {e}")
        raise HTTPException(status_code=500, detail=f"PDF generation failed: {e}")

    safe_title = "".join(c if c.isalnum() or c in " -_" else "_" for c in body.title)[:60]
    filename = f"{safe_title}.pdf"

    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )
